name: Blacklist Scan

on:
  pull_request:
    types:
      - opened
      - synchronize
  
jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Replace '3.x' with your desired Python version

      - name: Install requests dependencies
        run: python -m pip install requests
        
      - name: Set PR_NUMBER environment variable
        run: echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
      
      - name: Run blacklist scan
        id: scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python scan_pr.py
          if [[ $? != 0 ]]; then
            echo "::set-output name=scan-result::failed"
          else
            echo "::set-output name=scan-result::passed"
          fi

  fail-on-issue:
    needs: scan
    if: ${{ needs.scan.outputs.scan-result == 'failed' }}

    steps:
      - name: Fail the workflow
        run: exit 1
