name: Blacklist Scan

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Replace '3.x' with your desired Python version

      - name: Scan PR for blacklisted words
        run: |
          python -m pip install requests
          python scan_pr.py
