name: Blacklist Scan

on:
  pull_request:
    types:
      - opened
      - synchronize
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Replace '3.x' with your desired Python version

      - name: Install requests dependencies
        run: python -m pip install requests

      - name: Set PR_NUMBER environment variable
        run: echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Scan PR
        run: |
          python scan_pr.py
          if [ $? -eq 1 ]; then
            echo "Blacklist scan found issues."
            exit 1
          fi
